version: '2'
services:
    pruebacompletajhipster-app:
        image: pruebacompletajhipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pruebacompletajhipster-mysql:3306/pruebacompletajhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pruebacompletajhipster-mysql:
        extends:
            file: mysql.yml
            service: pruebacompletajhipster-mysql
